# Generated by Django 3.1.3 on 2020-11-21 15:12

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sch', '0002_school_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                                                                 geography=True, srid=4326),
        ),
    ]
