"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4fu=z7*^&s=tla4$)g-d%dwpt6=o#5d7^y!b4)p(8nqpa38gdh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    # 'grappelli',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "mapbox_location_field",
    "bootstrap4",

    'sch',
    'crispy_forms',
    'django.contrib.gis',
]
# INSTALLED_APPS += ("mapbox_location_field",)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'school_data',
        'USER': 'postgres',
        'PASSWORD': '12345687',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
MEDIA_URL = '/images/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')

MAPBOX_KEY = "pk.eyJ1Ijoic25laGFhYSIsImEiOiJja2d6ZXZhNXEwMWEyMnhwcTNyZG4zNnNpIn0.LVezZxqmWZH4QmJNtmXa_g"
CRISPY_TEMPLATE_PACK = 'bootstrap4'
GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')
IPCOUNTRY_APYKEY = [
    {  # free tier 2 querys per second
        "url": "http://api.ipinfodb.com/v3/ip-country/?ip={ip}&key={key}&format=json",
        "params": {
            "key": "****************************",
        },
        "fieldname": "countryCode",
    },
    {  # free tier 1.500 queries per day
        "url": "https://api.ipdata.co/{ip}?api-key={key}",
        "params": {
            "key": "*************************",
        },
        "fieldname": "country_code",
    },
    {  # free tier 10.000 queries per month and https is not suported in free tier
        "url": "http://api.ipstack.com/{ip}?access_key={key}",
        "params": {
            "key": "********************",
        },
        "fieldname": "country_code",
    },
]
